services:

  postgres:
    image: postgres:16-alpine
    container_name: axiom-postgres

    environment:
      POSTGRES_USER: axiom
      POSTGRES_PASSWORD: password
      POSTGRES_DB: axiom_db

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

    networks:
      - axiom-network

    restart: always

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U axiom -d axiom_db"]
      interval: 10s
      timeout: 5s
      retries: 5


  redis:
    image: redis:7-alpine
    container_name: axiom-redis

    command:
      redis-server --requirepass redispassword

    ports:
      - "6379:6379"

    volumes:
      - redis_data:/data

    networks:
      - axiom-network

    restart: always


  backend:
    build:
      context: ../backend

    container_name: axiom-api

    env_file:
      - ../backend/.env

    ports:
      - "8000:8000"

    depends_on:
      postgres:
        condition: service_healthy

      redis:
        condition: service_started

    networks:
      - axiom-network

    restart: always


volumes:
  postgres_data:
  redis_data:


networks:
  axiom-network:
    driver: bridge