"""rename email field in user table

Revision ID: 8462065c7162
Revises: fcbbc55ea8ce
Create Date: 2026-08-03 14:27:02.389745

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8462065c7162'
down_revision: Union[str, Sequence[str], None] = 'fcbbc55ea8ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email', sa.String(length=225), nullable=False))
    op.drop_index(op.f('ix_users_emai'), table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.drop_column('users', 'emai')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('emai', sa.VARCHAR(length=225), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index(op.f('ix_users_emai'), 'users', ['emai'], unique=True)
    op.drop_column('users', 'email')
    # ### end Alembic commands ###
