name: Axiom AI CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      
       postgres:
        image: postgres:16-alpine

        env:
          POSTGRES_USER: axiom
          POSTGRES_PASSWORD: password
          POSTGRES_DB: axiom_test

        ports:
          - 5432:5432

        options: >-
          --health-cmd "pg_isready -U axiom -d axiom_test"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        working-directory: backend
        run:
          pip install -r requirements.txt

      - name: Run tests
        working-directory: backend
        env:
         PYTHONPATH: .
         APP_NAME: ${{ secrets.APP_NAME }}
         ENVIRONMENT: ${{ secrets.ENVIRONMENT }}
         POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
         POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
         POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
         DATABASE_URL: postgresql+asyncpg://axiom:password@localhost:5432/axiom_test
         REDIS_URL: redis://localhost:6379
         LOGFIRE_TOKEN: ${{ secrets.LOGFIRE_TOKEN }}
         JWT_SECRET: ${{ secrets.JWT_SECRET }}
         JWT_ALGORITHM: ${{ secrets.JWT_ALGORITHM }}
        run:
          pytest

      - name: Build Docker image
        run:
          docker build -t axiom-api ./backend