name: Axiom AI CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main


jobs:

  test:

    runs-on: ubuntu-latest


    steps:

      - name: Checkout code
        uses: actions/checkout@v4


      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        working-directory: backend
        run:
          pip install -r requirements.txt



      - name: Run tests
        working-directory: backend
        env:
         PYTHONPATH: .
         APP_NAME: ${{ secrets.APP_NAME }}
         ENVIRONMENT: ${{ secrets.ENVIRONMENT }}
         POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
         POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
         POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
         DATABASE_URL: ${{ secrets.DATABASE_URL }}
         REDIS_URL: ${{ secrets.REDIS_URL }}
         LOGFIRE_TOKEN: ${{ secrets.LOGFIRE_TOKEN }}
         JWT_SECRET: ${{ secrets.JWT_SECRET }}
         JWT_ALGORITHM: ${{ secrets.JWT_ALGORITHM }}
        run:
          pytest


      - name: Build Docker image
        run:
          docker build -t axiom-api ./backend